CREATE USER DEV_USER INDENTIFIED BY DEV_USER_PWD DEFAULT TABLESPACE DEFAULT_TABLE_SPACE TEMPORARY TABLESPACE TEMP_TABLE_SPACE QUOTA 20M ON DEFAULT_TABLE_SPACE;

GRANT CREATE SESSION TO DEV_USER
GRANT CREATE TABLE TO DEV_USER;
GRANT CREATE VIEW TO DEV_USER;
GRANT CREATE ANY TRIGGER TO DEV_USER;
GRANT CREATE ANY PROCEDURE TO DEV_USER;
GRANT CREATE ANY SEQUENCE TO DEV_USER;
GRANT CREATE SYNONYM TO DEV_USER;


GRANT ALL ON OBJECT TO DEV_USER;
